<%-- !!DO_NOT_EDIT!! --%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
  // *** Get context path of web application ***
  String web_application = application.getContextPath();
%>
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="UTF-8" />
    <meta name="package" content="ielm_eltest_responsive" />
    <meta name="page_id" content="eltest_responsive_info" />
    <%-- Required metadata for JavaScript Module Navigation API --%>
    <jsp:include page="/WEB-INF/jsp/eltest-common-metadata.jsp" />
    <%-- ----------------------------------------------------------------- --%>
    <%-- Required external libs (scripts, style, img, ...) --%>
    <jsp:include page="/WEB-INF/jsp/external-libs.jsp" />
    <%-- Required libs for section: info --%>
    <jsp:include page="/WEB-INF/jsp/section-info-libs.jsp" />
    <%-- ----------------------------------------------------------------- --%>
    <%-- Required libs for component: version_info --%>
    <%@ taglib prefix="ielm" tagdir="/WEB-INF/tags/ielm" %>
    <%-- ELtest Cascading Style Sheets for design: Responsive --%>
    <link rel="stylesheet" type="text/css" href="<%=web_application%>/style/eltest/eltest-style.css" media="all and (min-width: 1281px)" />
    <link rel="stylesheet" type="text/css" href="<%=web_application%>/style/eltest/eltest-style1280.css" media="all and (max-width: 1280px) and (min-width: 601px)" />
    <link rel="stylesheet" type="text/css" href="<%=web_application%>/style/eltest/eltest-style600.css" media="all and (max-width: 600px)" />
    <link rel="stylesheet" type="text/css" href="<%=web_application%>/style/eltest/eltest.css" media="all" />
    <%-- ----------------------------------------------------------------- --%>
    <title>Info</title>
  </head>
  <body>
    <section>
      <header>
        <button type="button" class="btn btn-default" id="_ielm_open_navi"><span class="glyphicon glyphicon-menu-hamburger"></span></button>

        <div class="__logo_small">
          <!-- content generated by ielm-common-format.css (temporary not used) -->
        </div>
        Info
        <div class="_ielm_sub_header">
          <h3 id="_ielm_open_navi_desktop">Navigation</h3>
        </div>
      </header>

      <div id="content">

        <div id="_ielm_module_content">

          <div class="_ielm_navi">
            <div class="form-group" id="breadcrumb-list">
              <select class="form-control" id="__breadcrumb">
              </select>
            </div>
            <ul>
            </ul>
          </div>

          <div class="_inhalt">
          <!-- component: version_info -->
          <div>
            <ielm:VersionInfo 
              ielm = "Generiertes Modul zur Demonstration des Aufbaus eines iELMs im iELP"
              name = "eltest" 
              author = "Vorname Nachname"
              version = "0.0.1"
              date = "16.09.2022"
              lastmodifiedversion = "0.0.1" 
              lastmodifieddate = "16.09.2022"
              />                            						 
          </div>



          </div>

        </div>

      </div>




      <footer>
        <!-- content generated by ielp-navigation.js -->
      </footer>
    </section>

  </body>
</html>
