<%-- !!DO_NOT_EDIT!! --%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
  // *** Get context path of web application ***
  String web_application = application.getContextPath();
%>
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="UTF-8" />
    <meta name="package" content="ielm_eltest_responsive" />
    <meta name="page_id" content="eltest_responsive_online-help" />
    <%-- Required metadata for JavaScript Module Navigation API --%>
    <jsp:include page="/WEB-INF/jsp/eltest-common-metadata.jsp" />
    <%-- ----------------------------------------------------------------- --%>
    <%-- Required external libs (scripts, style, img, ...) --%>
    <jsp:include page="/WEB-INF/jsp/external-libs.jsp" />
    <%-- Required libs for section: online-help --%>
    <jsp:include page="/WEB-INF/jsp/section-online-help-libs.jsp" />
    <%-- ----------------------------------------------------------------- --%>

    <%-- ELtest Cascading Style Sheets for design: Responsive --%>
    <link rel="stylesheet" type="text/css" href="<%=web_application%>/style/eltest/eltest-style.css" media="all and (min-width: 1281px)" />
    <link rel="stylesheet" type="text/css" href="<%=web_application%>/style/eltest/eltest-style1280.css" media="all and (max-width: 1280px) and (min-width: 601px)" />
    <link rel="stylesheet" type="text/css" href="<%=web_application%>/style/eltest/eltest-style600.css" media="all and (max-width: 600px)" />
    <link rel="stylesheet" type="text/css" href="<%=web_application%>/style/eltest/eltest.css" media="all" />
    <%-- ----------------------------------------------------------------- --%>
    <title>Hilfe</title>
  </head>
  <body>
    <section>
      <header>
        <button type="button" class="btn btn-default" id="_ielm_open_navi"><span class="glyphicon glyphicon-menu-hamburger"></span></button>

        <div class="__logo_small">
          <!-- content generated by ielm-common-format.css (temporary not used) -->
        </div>
        Hilfe
        <div class="_ielm_sub_header">
          <h3 id="_ielm_open_navi_desktop">Navigation</h3>
        </div>
      </header>

      <div id="content">

        <div id="_ielm_module_content">

          <div class="_ielm_navi">
            <div class="form-group" id="breadcrumb-list">
              <select class="form-control" id="__breadcrumb">
              </select>
            </div>
            <ul>
            </ul>
          </div>

          <div class="_inhalt">


          <!-- component: inside_content_navigation -->
          <div class="_ielm_common_inside_content_navigation">
            <!-- content generated by ielm.inside.content.navigation.js -->
            <jsp:include page="/WEB-INF/jsp/online-help/eltest-online-help-start.jsp" />
          </div>

          </div>

        </div>

      </div>




      <footer>
        <!-- content generated by ielp-navigation.js -->
      </footer>
    </section>

  </body>
</html>
