<%-- !!DO_NOT_EDIT!! --%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
  // *** Get context path of web application ***
  String web_application = application.getContextPath();
%>
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="UTF-8" />
    <meta name="package" content="ielm_eltest_responsive" />
    <meta name="page_id" content="eltest_responsive_simulation" />
    <%-- Required metadata for JavaScript Module Navigation API --%>
    <jsp:include page="/WEB-INF/jsp/eltest-common-metadata.jsp" />
    <%-- ----------------------------------------------------------------- --%>
    <%-- Required external libs (scripts, style, img, ...) --%>
    <jsp:include page="/WEB-INF/jsp/external-libs.jsp" />
    <%-- Required libs for section: simulation --%>
    <jsp:include page="/WEB-INF/jsp/section-simulation-libs.jsp" />
    <%-- ----------------------------------------------------------------- --%>
    <%-- ELtest specific libs (Global/Model JavaScript) --%>
    <jsp:include page="/WEB-INF/jsp/eltest-specific-libs.jsp" />
	<%-- ELtest specific libs (View JavaScript) --%>
    <jsp:include page="/WEB-INF/jsp/section-simulation-view.jsp" />
	<%-- ELtest specific libs (Controller JavaScript) --%>
    <jsp:include page="/WEB-INF/jsp/section-simulation-controller.jsp" />
    <%-- ELtest Cascading Style Sheets for design: Responsive --%>
    <link rel="stylesheet" type="text/css" href="<%=web_application%>/style/eltest/eltest-style.css" media="all and (min-width: 1281px)" />
    <link rel="stylesheet" type="text/css" href="<%=web_application%>/style/eltest/eltest-style1280.css" media="all and (max-width: 1280px) and (min-width: 601px)" />
    <link rel="stylesheet" type="text/css" href="<%=web_application%>/style/eltest/eltest-style600.css" media="all and (max-width: 600px)" />
    <link rel="stylesheet" type="text/css" href="<%=web_application%>/style/eltest/eltest.css" media="all" />
    <%-- ----------------------------------------------------------------- --%>
    <title>Simulation</title>
  </head>
  <body>
    <section>
      <header>
        <button type="button" class="btn btn-default" id="_ielm_open_navi"><span class="glyphicon glyphicon-menu-hamburger"></span></button>
        <!-- component: menu -->
        <button type="button" class="btn btn-default" id="_ielm_open_menu"><span class="glyphicon glyphicon-cog"></span></button>
        <div class="__logo_small">
          <!-- content generated by ielm-common-format.css (temporary not used) -->
        </div>
        Simulation
        <div class="_ielm_sub_header">
          <h3 id="_ielm_open_navi_desktop">Navigation</h3>
        </div>
      </header>

      <div id="content">

        <div id="_ielm_module_content">

          <div class="_ielm_navi">
            <div class="form-group" id="breadcrumb-list">
              <select class="form-control" id="__breadcrumb">
              </select>
            </div>
            <ul>
            </ul>
          </div>

          <div class="_inhalt">

          <!-- component: menu -->
          <jsp:include page="/WEB-INF/jsp/eltest-simulation-menu-1.jsp" />
          <!-- next line inserted for adjusting first infobox -->        
          <p style="padding:0px; margin:0px; height:16px"></p>
          <!-- component: metabox -->
          <jsp:include page="/WEB-INF/jsp/eltest-metabox.jsp" />
          <!-- component: parameterbox -->
          <jsp:include page="/WEB-INF/jsp/eltest-parameterbox.jsp" />
          <!-- component: client_debug -->
          <!-- debug area in content area, should only be activated in web.xml if other debug utilities don't work -->
          <jsp:include page="/WEB-INF/jsp/ielm-client-debug-area.jsp" />
          <!-- component: content_workflow_view -->
          <jsp:include page="/WEB-INF/jsp/eltest-workflow-view.jsp" />

          </div>

        </div>

      </div>
      <!-- component: step_navigation -->
      <div class="_ielm_controls">

        <jsp:include page="/WEB-INF/jsp/eltest-simulation-step_navigation-1.jsp" >
          <jsp:param name="ielm_excecution_mode" value="simulation" />
        </jsp:include>
      </div>
      <footer>
        <!-- content generated by ielp-navigation.js -->
      </footer>
    </section>
    <!-- component: specific_libs -->
    <jsp:include page="/WEB-INF/jsp/eltest-pageload-finalization.jsp" />
    <script>
      gExecutionMode = gConstExecutionModeSimulation;
      eltest_set_init_information();
    </script>
  </body>
</html>
